// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg8cJTOd7cjPufbaBowy99pKs7b3JmkHQ',
    appId: '1:462827336300:web:example-app-id',
    messagingSenderId: '462827336300',
    projectId: 'sinhvien-3f1c7',
    authDomain: 'sinhvien-3f1c7.firebaseapp.com',
    databaseURL: 'https://sinhvien-3f1c7-default-rtdb.firebaseio.com',
    storageBucket: 'sinhvien-3f1c7.appspot.com',
    measurementId: 'G-EXAMPLE-ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8cJTOd7cjPufbaBowy99pKs7b3JmkHQ',
    appId: '1:462827336300:android:4e785e08b54c60d4229e49',
    messagingSenderId: '462827336300',
    projectId: 'sinhvien-3f1c7',
    databaseURL: 'https://sinhvien-3f1c7-default-rtdb.firebaseio.com',
    storageBucket: 'sinhvien-3f1c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg8cJTOd7cjPufbaBowy99pKs7b3JmkHQ',
    appId: '1:462827336300:ios:example-app-id',
    messagingSenderId: '462827336300',
    projectId: 'sinhvien-3f1c7',
    databaseURL: 'https://sinhvien-3f1c7-default-rtdb.firebaseio.com',
    storageBucket: 'sinhvien-3f1c7.appspot.com',
    iosBundleId: 'com.example.sinhvien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg8cJTOd7cjPufbaBowy99pKs7b3JmkHQ',
    appId: '1:462827336300:ios:example-app-id',
    messagingSenderId: '462827336300',
    projectId: 'sinhvien-3f1c7',
    databaseURL: 'https://sinhvien-3f1c7-default-rtdb.firebaseio.com',
    storageBucket: 'sinhvien-3f1c7.appspot.com',
    iosBundleId: 'com.example.sinhvien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg8cJTOd7cjPufbaBowy99pKs7b3JmkHQ',
    appId: '1:462827336300:web:example-app-id',
    messagingSenderId: '462827336300',
    projectId: 'sinhvien-3f1c7',
    authDomain: 'sinhvien-3f1c7.firebaseapp.com',
    databaseURL: 'https://sinhvien-3f1c7-default-rtdb.firebaseio.com',
    storageBucket: 'sinhvien-3f1c7.appspot.com',
    measurementId: 'G-EXAMPLE-ID',
  );
}
